simple-adblock: properly remove PROCD fw3 rules, option to unparallel DLs
Signed-off-by: Stan Grishin <stangri@melmac.net>

diff --git a/simple-adblock/files/simple-adblock.init b/simple-adblock/files/simple-adblock.init
--- a/simple-adblock/files/simple-adblock.init
+++ b/simple-adblock/files/simple-adblock.init
@@ -4,6 +4,7 @@ PKG_VERSION=
 
 export START=94
 export USE_PROCD=1
+export LC_ALL=C
 
 readonly packageName='simple-adblock'
 readonly serviceName="$packageName $PKG_VERSION"
@@ -15,8 +16,8 @@ export EXTRA_HELP="	check	Checks if specified domain is found in current blackli
 readonly A_TMP='/var/simple-adblock.hosts.a.tmp'
 readonly B_TMP='/var/simple-adblock.hosts.b.tmp'
 readonly CACHE_TMP='/var/simple-adblock.cache'
-readonly h_filter='/localhost/d;/^#/d;/^[^0-9]/d;s/^0\.0\.0\.0.//;s/^127\.0\.0\.1.//;s/[[:space:]]*#.*$//;s/[[:cntrl:]]$//;s/[[:space:]]//g;/[`~!@#\$%\^&\*()=+;:"'\'',<>?/\|[{}]/d;/]/d;/\./!d;/^$/d;'
-readonly d_filter='/^#/d;s/[[:space:]]*#.*$//;s/[[:space:]]*$//;s/[[:cntrl:]]$//;/[[:space:]]/d;/[`~!@#\$%\^&\*()=+;:"'\'',<>?/\|[{}]/d;/]/d;/\./!d;/^$/d;'
+readonly h_filter='/localhost/d;/^#/d;/^[^0-9]/d;s/^0\.0\.0\.0.//;s/^127\.0\.0\.1.//;s/[[:space:]]*#.*$//;s/[[:cntrl:]]$//;s/[[:space:]]//g;/[`~!@#\$%\^&\*()=+;:"'\'',<>?/\|[{}]/d;/]/d;/\./!d;/^$/d;/[^[:alnum:]_.-]/d;'
+readonly d_filter='/^#/d;s/[[:space:]]*#.*$//;s/[[:space:]]*$//;s/[[:cntrl:]]$//;/[[:space:]]/d;/[`~!@#\$%\^&\*()=+;:"'\'',<>?/\|[{}]/d;/]/d;/\./!d;/^$/d;/[^[:alnum:]_.-]/d;'
 readonly f_filter='s|^|local=/|;s|$|/|'
 readonly checkmark='\xe2\x9c\x93'
 readonly xmark='\xe2\x9c\x97'
@@ -27,7 +28,7 @@ readonly __FAIL__='\033[0;31m[\xe2\x9c\x97]\033[0m'
 readonly _ERROR_='\033[0;31mERROR\033[0m'
 
 create_lock() { [ -e "$PID" ] && return 1; touch "$PID"; }
-remove_lock() { [ -e "$PID" ] && rm -f "$PID"; rm -f /var/simple-adblock_tmp_* >/dev/null 2>&1; }
+remove_lock() { [ -e "$PID" ] && rm -f "$PID"; } # rm -f /var/simple-adblock_tmp_* >/dev/null 2>&1; }
 trap remove_lock EXIT
 output_ok() { case $verbosity in 1) output 1 "$_OK_";; 2) output 2 "$__OK__\n";; esac; }
 output_okn() { case $verbosity in 1) output 1 "$_OK_\n";; 2) output 2 "$__OK__\n";; esac; }
@@ -54,12 +55,13 @@ led_on(){ [[ -n "${1}" && -e "${1}/trigger" ]] && echo "default-on" > "${1}/trig
 led_off(){ [[ -n "${1}" && -e "${1}/trigger" ]] && echo "none" > "${1}/trigger" 2>&1; }
 boot() { load_package_config; ( sleep $bootDelay && rc_procd start_service && rc_procd service_triggers | cat & ); }
 
-export serviceEnabled verbosity forceDNS debug led wan_if wan_gw wanphysdev bootDelay dl_command serviceStatus
+export serviceEnabled verbosity forceDNS parallelDL debug led wan_if wan_gw wanphysdev bootDelay dl_command serviceStatus
 
 load_package_config() {
 	config_load "$packageName"
 	config_get_bool serviceEnabled 'config' 'enabled' 1
 	config_get_bool forceDNS       'config' 'force_dns' 1
+	config_get_bool parallelDL     'config' 'parallel_downloads' 1
 	config_get_bool debug          'config' 'debug' 0
 	config_get bootDelay           'config' 'boot_delay' '120'
 	config_get dlTimeout           'config' 'download_timeout' '20'
@@ -69,7 +71,7 @@ load_package_config() {
 		verbosity=1
 	fi
 	source /lib/functions/network.sh
-	dl_command="wget --no-check-certificate --timeout $dlTimeout -qO-"
+	dl_command="wget --no-check-certificate --timeout $dlTimeout -q"
 	led="${led:+/sys/class/leds/$led}"
 }
 
@@ -185,11 +187,12 @@ fw3_setup() {
 process_url() {
 	local label type D_TMP R_TMP
 	[[ -n "$1" && -n "$2" && -n "$3" ]] || return 1
-#	ping -W5 -c1 "$(echo $1 | awk -F '/' '{print $3}')" 1>/dev/null 2>/dev/null || { output_fail; return 1; }
+	#	ping -W5 -c1 "$(echo $1 | awk -F '/' '{print $3}')" 1>/dev/null 2>/dev/null || { output_fail; return 1; }
+	label="${1##*//}"; label="${label%%/*}";
 	if [ "$2" == "hosts" ]; then
-		label="Hosts: $(echo $1 | cut -d'/' -f3)" filter="$h_filter"
+		label="Hosts: $label"; filter="$h_filter";
 	else
-		label="Domains: $(echo $1 | cut -d'/' -f3)" filter="$d_filter"
+		label="Domains: $label"; filter="$d_filter";
 	fi
 	if [ "$3" == "blocked" ]; then
 		type='Blocked'; D_TMP="$B_TMP";
@@ -199,15 +202,15 @@ process_url() {
 	while [[ -z "$R_TMP" || -e "$R_TMP" ]]; do
 		R_TMP="/var/${packageName}_tmp_$(head -c40 /dev/urandom 2>/dev/null | tr -dc 'A-Za-z0-9' 2>/dev/null)"
 	done
-	if ! touch "$R_TMP" || ! $dl_command "$1" > "$R_TMP" 2>/dev/null; then
+	if ! $dl_command "$1" -O "$R_TMP" 2>/dev/null || [ ! -s "$R_TMP" ]; then
 		output 2 "[DL] $type $label $__FAIL__\n"
 		output 1 "$_FAIL_"
 		ubus_status add '-'
-		return 1
+		return 0
 	fi
 	sed -i "$filter" "$R_TMP"
-	cat "$R_TMP" >> "$D_TMP"
-	rm -f "$R_TMP" >/dev/null 2>/dev/null
+	cat "${R_TMP}" >> "$D_TMP"
+	rm -f "${R_TMP}" >/dev/null 2>/dev/null
 	output 2 "[DL] $type $label $__OK__\n"
 	output 1 "$_OK_"
 	ubus_status add '+'
@@ -233,17 +236,29 @@ download_lists() {
 	output 1 'Downloading lists '
 	if [ -n "$blacklist_hosts_urls" ]; then
 		for hf in ${blacklist_hosts_urls}; do
-			process_url "$hf" 'hosts' 'blocked' &
+			if [ $parallelDL -ne 0 ]; then
+				process_url "$hf" 'hosts' 'blocked' &
+			else
+				process_url "$hf" 'hosts' 'blocked'
+			fi
 		done
 	fi
 	if [ -n "$blacklist_domains_urls" ]; then
 		for hf in ${blacklist_domains_urls}; do
-			process_url "$hf" 'domains' 'blocked' &
+			if [ $parallelDL -ne 0 ]; then
+				process_url "$hf" 'domains' 'blocked' &
+			else
+				process_url "$hf" 'domains' 'blocked'
+			fi
 		done
 	fi
 	if [ -n "$whitelist_domains_urls" ]; then
 		for hf in ${whitelist_domains_urls}; do
-			process_url "$hf" 'domains' 'allowed' &
+			if [ $parallelDL -ne 0 ]; then
+				process_url "$hf" 'domains' 'allowed' &
+			else
+				process_url "$hf" 'domains' 'allowed'
+			fi
 		done
 	fi
 	wait
@@ -407,6 +422,7 @@ stop_service() {
 		reload_dnsmasq 'quiet'
 	fi
 	ubus_status set 'Stopped'
+	ubus call service set "{ \"name\": \"${packageName}\", \"instances\": { \"instance1\": { \"command\": [ \"/bin/true\" ],  \"data\": { \"firewall\": \"\" }}}}"
 	procd_set_config_changed firewall
 }
 
