vpn-policy-routing: ipset refactoring

diff --git a/vpn-policy-routing/files/vpn-policy-routing.init b/vpn-policy-routing/files/vpn-policy-routing.init
--- a/vpn-policy-routing/files/vpn-policy-routing.init
+++ b/vpn-policy-routing/files/vpn-policy-routing.init
@@ -17,14 +17,14 @@ readonly _WARNING_='\033[0;33mWARNING\033[0m'
 # readonly readmeURL="https://github.com/openwrt/packages/tree/master/net/vpn-policy-routing/files/README.md"
 readonly readmeURL="https://github.com/stangri/openwrt_packages/blob/master/vpn-policy-routing/files/README.md"
 
-export EXTRA_COMMANDS="status support"
+export EXTRA_COMMANDS='status support'
 export EXTRA_HELP="	support	Generates output required to troubleshoot routing issues
 		Use '-d' option for more detailed output
 		Use '-p' option to automatically upload data under VPR paste.ee account
 			WARNING: while paste.ee uploads are unlisted, they are still publicly available
 		List domain names after options to include their lookup in report"
 
-readonly packageName="vpn-policy-routing"
+readonly packageName='vpn-policy-routing'
 readonly serviceName="$packageName $PKG_VERSION"
 readonly PID="/var/run/${packageName}.pid"
 readonly JsonFile="/var/run/${packageName}.json"
@@ -58,7 +58,7 @@ output() {
 is_installed() { [ -n "$(opkg list-installed "$1")" ]; }
 
 export serviceEnabled verbosity strictMode wanTableID wanMark fwMask
-export ipv6Enabled localIpset remoteIpset ipruleEnabled dnsmasqIpset icmpIface
+export ipv6Enabled localIpset remoteIpset ipruleEnabled icmpIface
 export ignoredIfaces="" supportedIfaces=""
 export appendLocalPolicy="" appendRemotePolicy=""
 export wanIface4 wanIface6 ifaceMark ifaceTableID ifacesListAll ifacesListSupported wanGW4 wanGW6
@@ -80,7 +80,6 @@ vpr_find_true() {
 	fi
 	eval "$1=${iface:-$i}"
 }
-
 vpr_get_gateway() {
 	local iface="$2" dev="$3" gw
 	network_get_gateway gw "$iface"
@@ -97,7 +96,6 @@ vpr_get_gateway6() {
 	fi
 	eval "$1=${gw}"
 }
-
 is_l2tp() { local proto; proto=$(uci -q get network."$1".proto); [ "${proto:0:4}" = "l2tp" ]; }
 is_oc() { local proto; proto=$(uci -q get network."$1".proto); [ "${proto:0:11}" = "openconnect" ]; }
 is_ovpn() { local dev; dev=$(uci -q get network."$1".ifname); [ "${dev:0:3}" = "tun" ] || [ "${dev:0:3}" = "tap" ] || [ -f "/sys/devices/virtual/net/${dev}/tun_flags" ]; }
@@ -133,10 +131,9 @@ load_package_config() {
 	config_get_bool serviceEnabled      'config' 'enabled' 0
 	config_get_bool strictMode          'config' 'strict_enforcement' 1
 	config_get_bool ipv6Enabled         'config' 'ipv6_enabled' 0
-	config_get_bool dnsmasqIpset        'config' 'dnsmasq_ipset' 0
-	config_get_bool remoteIpset         'config' 'remote_ipset' 1
 	config_get_bool localIpset          'config' 'local_ipset' 0
 	config_get_bool ipruleEnabled       'config' 'iprule_enabled' 0
+	config_get remoteIpset              'config' 'remote_ipset'
 	config_get appendLocalPolicy        'config' 'append_local_rules'
 	config_get appendRemotePolicy       'config' 'append_remote_rules'
 	config_get verbosity                'config' 'verbosity' '2'
@@ -153,11 +150,6 @@ load_package_config() {
 		verbosity=1
 	fi
 
-	case $insertOption in
-		insert|-i|-I) insertOption="-I";;
-		append|-a|-A|*) insertOption="-A";;
-	esac
-
 	. /lib/functions/network.sh
 	. /usr/share/libubox/jshn.sh
 	vpr_find_true wanIface4 'wan'
@@ -170,19 +162,48 @@ load_package_config() {
 is_enabled() {
 	load_package_config
 	if [ "$serviceEnabled" -eq 0 ]; then
-		if [ "$1" = "on_start" ]; then
+		if [ "$1" = 'on_start' ]; then
 			output "$packageName is currently disabled.\\n"
 			output "Run the following commands before starting service again:\\n"
 			output "uci set $packageName.config.enabled='1'; uci commit;\\n"
 		fi
 		return 1
 	fi
-	if [ "$dnsmasqIpset" -ne 0 ]; then
-		if ! dnsmasq --version 2>/dev/null | grep -q -w "ipset"; then
-			output "$_ERROR_: dnsmasq support is enabled in $packageName, but dnsmasq is either not installed or installed dnsmasq does not support ipsets!\\n"
-			dnsmasqIpset=0
+
+	case $insertOption in
+		insert|-i|-I) insertOption='-I';;
+		append|-a|-A|*) insertOption='-A';;
+	esac
+
+	case $remoteIpset in
+		ipset)
+			if ! ipset help hash:net >/dev/null 2>&1; then
+				output "$_ERROR_: ipset support is enabled in $packageName, but ipset is either not installed or installed ipset does not support 'hash:net' type!\\n"
+				unset remoteIpset
+			fi
+			;;
+		dnsmasq.ipset)
+			if ! dnsmasq --version 2>/dev/null | grep -q -w 'ipset'; then
+				output "$_ERROR_: DNSMASQ ipset support is enabled in $packageName, but DNSMASQ is either not installed or installed DNSMASQ does not support ipsets!\\n"
+				unset remoteIpset
+			fi
+			if ! ipset help hash:net >/dev/null 2>&1; then
+				output "$_ERROR_: DNSMASQ ipset support is enabled in $packageName, but ipset is either not installed or installed ipset does not support 'hash:net' type!\\n"
+				unset remoteIpset
+			fi
+			;;
+		*) unset remoteIpset;;
+	esac
+	
+	if [ "$localIpset" -ne 0 ]; then
+		if ! ipset help hash:net >/dev/null 2>&1; then
+			output "$_ERROR_: Local ipset support is enabled in $packageName, but ipset is either not installed or installed ipset does not support 'hash:net' type!\\n"
+			unset localIpset
 		fi
-		remoteIpset=1
+		if ! ipset help hash:mac >/dev/null 2>&1; then
+			output "$_ERROR_: Local ipset support is enabled in $packageName, but ipset is either not installed or installed ipset does not support 'hash:mac' type!\\n"
+			unset localIpset
+		fi
 	fi
 }
 
@@ -231,47 +252,40 @@ ipt() {
 
 # shellcheck disable=SC2086
 ips() {
-	local command="$1" ipset="${2//-/_}" param="$3" comment="$4" appendix failFlagIpv4=0 failFlagIpv6=0
+	local command="$1" ipset="${2//-/_}" param="$3" comment="$4" appendix failFlag=0
 	if [ "${ipset//_ip}" != "${ipset}" ]; then
 		ipset="${ipset//_ip}"; appendix='_ip';
 	elif [ "${ipset//_mac}" != "${ipset}" ]; then
 		ipset="${ipset//_mac}"; appendix='_mac';
 	fi
 
+	if [ "$command" = "add_dnsmasq" ]; then
+		[ "$remoteIpset" != 'dnsmasq.ipset' ] && return 1
+#	elif [ "$command" = "add_unbound" ]; then
+#		[ "$remoteIpset" != 'unbound.ipset' ] && return 1
+	else
+		if [[ -z "$appendix" && -z "$remoteIpset" ]] || \
+			 [[ -n "$appendix" && "$localIpset" -eq 0 ]]; then
+		 	return 1
+		fi
+	fi
+
 	case "$command" in
 		add_dnsmasq)
-			[ "$dnsmasqIpset" -eq 0 ] && return 1
-			[ "$ipv6Enabled" -ne 0 ] && ipset="${ipset},${ipset}6"
-			echo "ipset=/${param}/${ipset} # $comment" >> "$dnsmasqFile" || failFlagIpv4=1
-			if [ "$failFlagIpv4" -eq 0 ] && [ "$failFlagIpv6" -eq 0 ]; then return 0; else return 1; fi
+			echo "ipset=/${param}/${ipset} # $comment" >> "$dnsmasqFile" || failFlag=1
 			;;
 		add)
-			if [ -z "$appendix" ]; then
-				[ "$remoteIpset" -eq 0 ] && return 1
-			else
-				[ "$localIpset" -eq 0 ] && return 1
-			fi
-			ipset -q -! $command "${ipset}${appendix}" $param comment "$comment" || failFlagIpv4=1
-			[ "$ipv6Enabled" -ne 0 ] && ipset -q -! "$command" "${ipset}6${appendix}" ${param/"family inet"/"family inet6"} comment "$comment" || failFlagIpv6=1
-			if [ "$failFlagIpv4" -eq 0 ] || [ "$failFlagIpv6" -eq 0 ]; then return 0; else return 1; fi
+			ipset -q -! $command "${ipset}${appendix}" $param comment "$comment" || failFlag=1
 			;;
 		create)
-			if [ -z "$appendix" ]; then
-				[ "$remoteIpset" -eq 0 ] && return 0
-			else
-				[ "$localIpset" -eq 0 ] && return 0
-			fi
-			ipset -q -! "$command" "${ipset}${appendix}" $param || failFlagIpv4=1
-			if [ "$ipv6Enabled" -ne 0 ]; then ipset -q -! "$command" "${ipset}6${appendix}" ${param/"family inet"/"family inet6"} || failFlagIpv6=1; fi
-			if [ "$failFlagIpv4" -eq 0 ] && [ "$failFlagIpv6" -eq 0 ]; then return 0; else return 1; fi
+			ipset -q -! "$command" "${ipset}${appendix}" $param || failFlag=1
 			;;
 		destroy|flush)
-			ipset -q -! "$command" "${ipset}${appendix}" || failFlagIpv4=1
-			if [ "$ipv6Enabled" -ne 0 ]; then ipset -q -! "$command" "${ipset}6${appendix}" || failFlagIpv6=1; fi
+			ipset -q -! "$command" "${ipset}${appendix}" 2>/dev/null || failFlag=1
 			return 0
-			if [ "$failFlagIpv4" -eq 0 ] && [ "$failFlagIpv6" -eq 0 ]; then return 0; else return 1; fi
 			;;
 	esac
+	return $failFlag
 }
 
 ipr()
@@ -472,75 +486,75 @@ table_destroy(){
 
 # shellcheck disable=SC2086
 table_create(){
-	local tid="$1" mark="$2" iface="$3" gw4="$4" dev="$5" gw6="$6" dev6="$7" dscp s=0 i ipv4_set=0 ipv6_set=0 ipv4_error=0 ipv6_error=0
+	local tid="$1" mark="$2" iface="$3" gw4="$4" dev="$5" gw6="$6" dev6="$7" dscp s=0 i ipv4_error=0 ipv6_error=0
 
-	if [ -n "$tid" ] && [ -n "$mark" ] && [ -n "$iface" ]; then
-		table_destroy "$tid" "$iface" "$mark"
+	if [ -z "$tid" ] || [ -z "$mark" ] || [ -z "$iface" ]; then
+		return 1
+	fi
 
-		if [ -n "$gw4" ] || [ "$strictMode" -ne 0 ]; then
-			if [ -z "$gw4" ]; then
-				ip -4 route add unreachable default table "$tid" >/dev/null 2>&1 || ipv4_error=1
+	table_destroy "$tid" "$iface" "$mark"
+
+	if [ -n "$gw4" ] || [ "$strictMode" -ne 0 ]; then
+		if [ -z "$gw4" ]; then
+			ip -4 route add unreachable default table "$tid" >/dev/null 2>&1 || ipv4_error=1
+		else
+			ip -4 route add default via "$gw4" dev "$dev" table "$tid" >/dev/null 2>&1 || ipv4_error=1
+		fi
+		ip -4 route ls table main | grep -v 'br-lan' | while read -r i; do
+			idev="$(echo "$i" | grep -Eso 'dev [^ ]*' | awk '{print $2}')"
+			if ! is_supported_iface_dev "$idev"; then
+				ip -4 route add $i table "$tid" >/dev/null 2>&1 || ipv4_error=1
+			fi
+		done
+		ip -4 route flush cache || ipv4_error=1
+		ip -4 rule add fwmark "$mark" table "$tid" || ipv4_error=1
+	fi
+
+	if [ "$ipv6Enabled" -ne 0 ]; then
+		if { [ -n "$gw6" ] && [ "$gw6" != "::/0" ]; } || [ "$strictMode" -ne 0 ]; then
+			if [ -z "$gw6" ] || [ "$gw6" = "::/0" ]; then
+				ip -6 route add unreachable default table "$tid" || ipv6_error=1
 			else
-				ip -4 route add default via "$gw4" dev "$dev" table "$tid" >/dev/null 2>&1 || ipv4_error=1
+				ip -6 route ls table main | grep " dev $dev6 " | while read -r i; do
+					ip -6 route add $i table "$tid" >/dev/null 2>&1 || ipv6_error=1
+				done
 			fi
-			ip -4 route ls table main | grep -v 'br-lan' | while read -r i; do
-				idev="$(echo "$i" | grep -Eso 'dev [^ ]*' | awk '{print $2}')"
-				if ! is_supported_iface_dev "$idev"; then
-					ip -4 route add $i table "$tid" >/dev/null 2>&1 || ipv4_error=1
-				fi
-			done
-			ip -4 route flush cache || ipv4_error=1
-			ip -4 rule add fwmark "$mark" table "$tid" || ipv4_error=1
-			[ "$ipv4_error" -eq 0 ] && ipv4_set=1 || s=$ipv4_error
-		fi
-
-		if [ "$ipv6Enabled" -ne 0 ]; then
-			if { [ -n "$gw6" ] && [ "$gw6" != "::/0" ]; } || [ "$strictMode" -ne 0 ]; then
-				if [ -z "$gw6" ] || [ "$gw6" = "::/0" ]; then
-					ip -6 route add unreachable default table "$tid" || ipv6_error=1
-				else
-					ip -6 route ls table main | grep " dev $dev6 " | while read -r i; do
-						ip -6 route add $i table "$tid" >/dev/null 2>&1 || ipv6_error=1
-					done
-				fi
-				ip -6 route flush cache || ipv6_error=1
-				ip -6 rule add fwmark "$mark" table "$tid" || ipv6_error=1
-				s=$ipv6_error
-				[ "$ipv6_error" -eq 0 ] && ipv6_set=1 || s=$ipv6_error
-			fi
-		fi
-
-		if [ $ipv4_set -ne 0 ] || [ $ipv6_set -ne 0 ]; then
-			dscp="$(uci -q get "${packageName}".config."${iface}"_dscp)"
-			if [ "${dscp:-0}" -ge 1 ] && [ "${dscp:-0}" -le 63 ]; then
-				ipt -t mangle -I VPR_PREROUTING -m dscp --dscp "${dscp}" -j MARK --set-xmark "${mark}/${fwMask}" || s=1
-			fi
-			if [ $remoteIpset -ne 0 ]; then
-				ips 'create' "${iface}" 'hash:net family inet comment' && ips 'flush' "${iface}" || s=1
-				if [ "$ipv4_set" -ne 0 ]; then
-					ipt -t mangle -I VPR_PREROUTING -m set --match-set "${iface}" dst -j MARK --set-xmark "${mark}/${fwMask}" || s=1
-				fi
-				if [ "$ipv6_set" -ne 0 ]; then
-					ipt -t mangle -I VPR_PREROUTING -m set --match-set "${iface}6" dst -j MARK --set-xmark "${mark}/${fwMask}" || s=1
-				fi
-			fi
-			if [ "$localIpset" -ne 0 ]; then
-				ips 'create' "${iface}_ip" 'hash:net family inet comment' && ips 'flush' "${iface}_ip" || s=1
-				ips 'create' "${iface}_mac" 'hash:mac comment' && ips 'flush' "${iface}_mac" || s=1
-				if [ "$ipv4_set" -ne 0 ]; then
-					ipt -t mangle -I VPR_PREROUTING -m set --match-set "${iface}_ip" src -j MARK --set-mark "${mark}/${fwMask}" || s=1
-					ipt -t mangle -I VPR_PREROUTING -m set --match-set "${iface}_mac" src -j MARK --set-mark "${mark}/${fwMask}" || s=1
-				fi
-				if [ "$ipv6_set" -ne 0 ]; then
-					ipt -t mangle -I VPR_PREROUTING -m set --match-set "${iface}6_ip" src -j MARK --set-xmark "${mark}/${fwMask}" || s=1
-					ipt -t mangle -I VPR_PREROUTING -m set --match-set "${iface}6_mac" src -j MARK --set-xmark "${mark}/${fwMask}" || s=1
-				fi
-			fi
-			if [ "$iface" = "$icmpIface" ]; then
-				ipt -t mangle -I VPR_OUTPUT -p icmp -j MARK --set-xmark "${mark}/${fwMask}" || s=1
-			fi
+			ip -6 route flush cache || ipv6_error=1
+			ip -6 rule add fwmark "$mark" table "$tid" || ipv6_error=1
 		fi
 	fi
+
+	if [ $ipv4_error -eq 0 ] || [ $ipv6_error -eq 0 ]; then
+		dscp="$(uci -q get "${packageName}".config."${iface}"_dscp)"
+		if [ "${dscp:-0}" -ge 1 ] && [ "${dscp:-0}" -le 63 ]; then
+			ipt -t mangle -I VPR_PREROUTING -m dscp --dscp "${dscp}" -j MARK --set-xmark "${mark}/${fwMask}" || s=1
+		fi
+		if [ -n "$remoteIpset" ]; then
+			if ips 'create' "${iface}" 'hash:net comment' && ips 'flush' "${iface}"; then
+				ipt -t mangle -I VPR_PREROUTING -m set --match-set "${iface}" dst -j MARK --set-xmark "${mark}/${fwMask}" || s=1
+			else
+			s=1
+			fi
+		fi
+		if [ "$localIpset" -ne 0 ]; then
+			if ips 'create' "${iface}_ip" 'hash:net comment' && ips 'flush' "${iface}_ip"; then
+				ipt -t mangle -I VPR_PREROUTING -m set --match-set "${iface}_ip" src -j MARK --set-mark "${mark}/${fwMask}" || s=1
+			else
+			s=1
+			fi
+			if ips 'create' "${iface}_mac" 'hash:mac comment' && ips 'flush' "${iface}_mac"; then
+				ipt -t mangle -I VPR_PREROUTING -m set --match-set "${iface}_mac" src -j MARK --set-mark "${mark}/${fwMask}" || s=1
+			else
+			s=1
+			fi
+		fi
+		if [ "$iface" = "$icmpIface" ]; then
+			ipt -t mangle -I VPR_OUTPUT -p icmp -j MARK --set-xmark "${mark}/${fwMask}" || s=1
+		fi
+	else
+		s=1
+	fi
+
 	return $s
 }
 
@@ -567,7 +581,6 @@ process_interface(){
 			ifaceTableID="$((ifaceTableID + 1))"; ifaceMark="$(printf '0x%06x' $((ifaceMark + wanMark)))";
 			;;
 		create)
-			output 2 "Creating table '$displayText' "
 			eval "mark_${iface//-/_}=$ifaceMark"; eval "tid_${iface//-/_}=$ifaceTableID";
 			table_destroy "${ifaceTableID}" "${iface}"
 			vpr_get_gateway gw4 "$iface" "$dev"
@@ -578,6 +591,7 @@ process_interface(){
 				displayText="${iface}/${dev}/${gw4:-0.0.0.0}"
 			fi
 			[ "$ipv6Enabled" -ne 0 ] && displayText="${displayText}/${gw6:-::/0}"
+			output 2 "Creating table '$displayText' "
 			is_default_dev "$dev" && displayText="${displayText}${__OK__}"
 			if table_create "$ifaceTableID" "$ifaceMark" "$iface" "$gw4" "$dev" "$gw6" "$dev6"; then
 				serviceStatusSummary="${serviceStatusSummary}${displayText} "
@@ -625,6 +639,19 @@ convert_config(){
 	sed -i 's/remote_ports/remote_port/g' "/etc/config/${packageName}"
 	sed -i 's/ipset_enabled/remote_ipset/g' "/etc/config/${packageName}"
 	sed -i 's/dnsmasq_enabled/dnsmasq_ipset/g' "/etc/config/${packageName}"
+	config_load "$packageName"
+	config_get_bool dnsmasqIpset        'config' 'dnsmasq_ipset' 0
+	config_get      remoteIpset         'config' 'remote_ipset'
+	if [ "$dnsmasqIpset" = "1" ]; then
+		remoteIpset="dnsmasq.ipset";
+	elif [ "$remoteIpset" = "1" ]; then
+		remoteIpset="ipset";
+	elif [ "$remoteIpset" = "0" ]; then
+		remoteIpset=""
+	fi
+	uci -q del "$packageName.config.dnsmasq_ipset"
+	uci -q set "$packageName".config.remote_ipset="$remoteIpset"
+	uci commit "$packageName"
 	for i in udp_proto_enabled forward_chain_enabled input_chain_enabled output_chain_enabled; do
 		grep -q "$i" "/etc/config/${packageName}" && output "${_WARNING_}: $i setting is not supported in ${serviceName}.\\n"
 	done
@@ -660,6 +687,7 @@ process_user_file(){
 		output_fail
 		return 1
 	else
+		output 2 "Running $path "
 		output_ok
 		return 0
 	fi
