vpn-policy-routing: allow all protocols

diff --git a/vpn-policy-routing/files/vpn-policy-routing.init b/vpn-policy-routing/files/vpn-policy-routing.init
--- a/vpn-policy-routing/files/vpn-policy-routing.init
+++ b/vpn-policy-routing/files/vpn-policy-routing.init
@@ -17,7 +17,7 @@ readonly _WARNING_='\033[0;33mWARNING\033[0m'
 # readonly readmeURL="https://github.com/openwrt/packages/tree/master/net/vpn-policy-routing/files/README.md"
 readonly readmeURL="https://github.com/stangri/openwrt_packages/blob/master/vpn-policy-routing/files/README.md"
 
-export EXTRA_COMMANDS='status support'
+export EXTRA_COMMANDS='support'
 export EXTRA_HELP="	support	Generates output required to troubleshoot routing issues
 		Use '-d' option for more detailed output
 		Use '-p' option to automatically upload data under VPR paste.ee account
@@ -83,7 +83,7 @@ vpr_find_true() {
 vpr_get_gateway() {
 	local iface="$2" dev="$3" gw
 	network_get_gateway gw "$iface"
-	if [ -z "$gw" ]; then
+	if [ -z "$gw" ] || [ "$gw" = '0.0.0.0' ]; then
 		gw="$(ip -4 a list dev "$dev" 2>/dev/null | grep inet | awk '{print $2}' | awk -F "/" '{print $1}')"
 	fi
 	eval "$1=${gw}"
@@ -91,7 +91,7 @@ vpr_get_gateway() {
 vpr_get_gateway6() {
 	local iface="$2" dev="$3" gw
 	network_get_gateway6 gw "$iface"
-	if [ -z "$gw" ]; then
+	if [ -z "$gw" ] || [ "$gw" = '::/0' ] || [ "$gw" = '::0/0' ]; then
 		gw="$(ip -6 a list dev "$dev" 2>/dev/null | grep inet6 | awk '{print $2}')"
 	fi
 	eval "$1=${gw}"
@@ -129,6 +129,7 @@ is_supported_iface_dev() {
 	done
 	return 1
 }
+is_supported_protocol () { grep -o '^[^#]*' /etc/protocols | grep . | awk '{print $1}' | grep -q "$1"; }
 
 load_package_config() {
 	config_load "$packageName"
@@ -294,8 +295,8 @@ ips() {
 
 ipr()
 {
-	local comment="$1" tid=$(eval echo "\$tid_${2//-/_}") laddr="$3" failFlagIpv4=0 failFlagIpv6=1
 	[ "$ipruleEnabled" -ne 0 ] || return 1
+	local comment="$1" tid=$(eval echo "\$tid_${2//-/_}") laddr="$3" failFlagIpv4=0 failFlagIpv6=1
 	ip -4 rule del from "$laddr" table "$tid" >/dev/null 2>&1
 	ip -4 rule add from "$laddr" table "$tid" >/dev/null 2>&1 || failFlagIpv4=1
 	if [ "$ipv6Enabled" -ne 0 ]; then
@@ -306,9 +307,9 @@ ipr()
 }
 
 insert_tor_policy() {
-	local comment="$1" iface="$2" laddr="$3" lport="$4" raddr="$5" rport="$6" proto="${7:-tcp}" chain="${8:-PREROUTING}"
+	local comment="$1" iface="$2" laddr="$3" lport="$4" raddr="$5" rport="$6" proto="${7:-all}" chain="${8:-PREROUTING}"
 	local mark=$(eval echo "\$mark_${iface//-/_}")
-	[ -z "$mark" ] && processPolicyStatus="${processPolicyStatus}${_ERROR_}: unknown fw_mark for ${iface}!\\n"
+	[ -z "$mark" ] && processPolicyError="${processPolicyError}${_ERROR_}: unknown fw_mark for ${iface}!\\n"
 	param="-t mangle $insertOption VPR_${chain} 1 -j MARK --set-xmark ${mark}/${fwMask}"
 	[ -n "$laddr" ] && param="$param -s $laddr"
 	[ -n "$lport" ] && param="$param -p tcp -m multiport --sport ${lport//-/:}"
@@ -320,7 +321,7 @@ insert_tor_policy() {
 }
 
 insert_policy() {
-	local comment="$1" iface="$2" laddr="$3" lport="$4" raddr="$5" rport="$6" proto="${7:-tcp}" chain="${8:-PREROUTING}"
+	local comment="$1" iface="$2" laddr="$3" lport="$4" raddr="$5" rport="$6" proto="${7:-all}" chain="${8:-PREROUTING}"
 	local mark=$(eval echo "\$mark_${iface//-/_}") param i
 	if [ "$ipv6Enabled" -eq 0 ]; then
 		is_ipv6 "$laddr" && return 0
@@ -328,40 +329,45 @@ insert_policy() {
 	fi
 
 	if [ -z "$mark" ]; then
-		processPolicyStatus="${processPolicyStatus}${_ERROR_}: unknown fw_mark for ${iface}!\\n"
+		processPolicyError="${processPolicyError}${_ERROR_}: unknown fw_mark for ${iface}!\\n"
 		return 0
 	fi
 
-	for i in tcp udp; do
-		if [ "${proto//$i}" != "$proto" ]; then
+	for i in $proto; do
+		if [ "$i" = 'all' ]; then
+			param="-t mangle -I VPR_${chain} -j MARK --set-xmark ${mark}/${fwMask}"
+		elif ! is_supported_protocol "$i"; then
+			processPolicyError="${processPolicyError}${_ERROR_}: unknown protocol '$i' in policy '$comment'\\n"
+			return 0
+		else
 			param="-t mangle -I VPR_${chain} -j MARK --set-xmark ${mark}/${fwMask} -p $i"
-			if [ -n "$laddr" ]; then
-				if is_phys_dev "$laddr"; then
-					param="$param -i ${laddr:1}"
-				elif is_mac_address "$laddr"; then
-					param="$param -m mac --mac-source $laddr"
-				else
-					param="$param -s $laddr"
-				fi
-				if [ "${appendLocalPolicy//-d}" != "$appendLocalPolicy" ] && [ -n "$raddr" ]; then
-					processPolicyStatus="${processPolicyStatus}${_ERROR_}: cannot append '$comment' policy with '$appendLocalPolicy' as destination is already set to '$raddr'\\n"
-				else
-					param="$param $appendLocalPolicy"
-				fi
-			fi
-			[ -n "$lport" ] && param="$param -m multiport --sport ${lport//-/:}"
-			if [ -n "$raddr" ]; then 
-				if [ "${appendRemotePolicy//-s}" != "$appendRemotePolicy" ] && [ -n "$laddr" ]; then
-					param="$param -d $raddr"
-					processPolicyStatus="${processPolicyStatus}${_ERROR_}: cannot append '$comment' policy with '$appendRemotePolicy' as source is already set to '$laddr'\\n"
-				else
-					param="$param -d $raddr $appendRemotePolicy"
-				fi
-			fi
-			[ -n "$rport" ] && param="$param -m multiport --dport ${rport//-/:}"
-			[ -n "$comment" ] && param="$param -m comment --comment $(echo "$comment" | tr '[\. ~`!@#$%^&*()\+/,<>?//;:]' '_')"
-			ipt "$param" || processPolicyStatus="${processPolicyStatus}${_ERROR_}: iptables $param\\n"
 		fi
+		if [ -n "$laddr" ]; then
+			if is_phys_dev "$laddr"; then
+				param="$param -i ${laddr:1}"
+			elif is_mac_address "$laddr"; then
+				param="$param -m mac --mac-source $laddr"
+			else
+				param="$param -s $laddr"
+			fi
+			if [ "${appendLocalPolicy//-d}" != "$appendLocalPolicy" ] && [ -n "$raddr" ]; then
+				processPolicyError="${processPolicyError}${_ERROR_}: cannot append '$comment' policy with '$appendLocalPolicy' as destination is already set to '$raddr'\\n"
+			else
+				param="$param $appendLocalPolicy"
+			fi
+		fi
+		[ -n "$lport" ] && param="$param -m multiport --sport ${lport//-/:}"
+		if [ -n "$raddr" ]; then 
+			if [ "${appendRemotePolicy//-s}" != "$appendRemotePolicy" ] && [ -n "$laddr" ]; then
+				param="$param -d $raddr"
+				processPolicyError="${processPolicyError}${_ERROR_}: cannot append '$comment' policy with '$appendRemotePolicy' as source is already set to '$laddr'\\n"
+			else
+				param="$param -d $raddr $appendRemotePolicy"
+			fi
+		fi
+		[ -n "$rport" ] && param="$param -m multiport --dport ${rport//-/:}"
+		[ -n "$comment" ] && param="$param -m comment --comment $(echo "$comment" | tr '[\. ~`!@#$%^&*()\+/,<>?//;:]' '_')"
+		ipt "$param" || processPolicyError="${processPolicyError}${_ERROR_}: iptables $param\\n"
 	done
 	return 0
 }
@@ -390,23 +396,38 @@ r_process_policy(){
 		insert_policy "$comment" "$iface" "$laddr" "$lport" "$raddr" "$rport" "$proto" "$chain"
 	elif is_phys_dev "$laddr"; then
 		insert_policy "$comment" "$iface" "$laddr" "$lport" "$raddr" "$rport" "$proto" "$chain"
-	elif [ -n "$laddr" ] && [ -z "$lport" ] && [ -z "$raddr" ] && [ -z "$rport" ] && [ "$proto" = "tcp" ] && [ "$chain" = "PREROUTING" ]; then
+	elif [ -n "$laddr" ] && [ -z "$lport" ] && [ -z "$raddr" ] && [ -z "$rport" ] && [ "$chain" = 'PREROUTING' ]; then
 		if is_mac_address "$laddr"; then
+			if [ "$proto" != 'all' ] && [ "$localIpset" -ne 0 ]; then
+				processPolicyWarning="${processPolicyWarning}${_WARNING_}: please set 'proto' to 'all' for policy '$comment', mac-address '$laddr'.\\n"
+			fi
 			ips 'add' "${iface}_mac" "$laddr" "${comment}: $laddr" || ipsFailFlag=1
 		else
-			for i in $(resolveip "$laddr"); do
-				ips 'add' "${iface}_ip" "$i" "${comment}: $laddr $i" || \
-				ipr "$comment" "$iface" "$i" || \
-				insert_policy "$comment" "$iface" "$i" "$lport" "$raddr" "$rport" "$proto" "$chain"
-			done
+			if [ "$proto" != "all" ] && [ "$localIpset" -ne 0 ]; then
+				processPolicyWarning="${processPolicyWarning}${_WARNING_}: please set 'proto' to 'all' for policy '$comment', address '$laddr'.\\n"
+			fi
+			if ! ips 'add' "${iface}_ip" "$laddr" "${comment}: $laddr"; then
+				for i in $(resolveip "$laddr"); do
+					ipr "$comment" "$iface" "$i" || \
+					insert_policy "$comment" "$iface" "$i" "$lport" "$raddr" "$rport" "$proto" "$chain"
+				done
+			fi
 		fi
-	elif [ -z "$laddr" ] && [ -z "$lport" ] && [ -n "$raddr" ] && [ -z "$rport" ] && [ "$proto" = "tcp" ] && [ "$chain" = "PREROUTING" ]; then
+	elif [ -z "$laddr" ] && [ -z "$lport" ] && [ -n "$raddr" ] && [ -z "$rport" ] && [ "$chain" = 'PREROUTING' ]; then
 		if is_domain "$raddr"; then
-			if ! ips "add_dnsmasq" "${iface}" "$raddr" "${comment}"; then
-				for i in $(resolveip "$raddr"); do ips "add" "${iface}" "$raddr" "${comment}: $raddr" || ipsFailFlag=1; done
+			if [ -n "$remoteIpset" ]; then
+				if [ "$proto" != 'all' ]; then
+					processPolicyWarning="${processPolicyWarning}${_WARNING_}: please set 'proto' to 'all' for policy '$comment', domain '$raddr'.\\n"
+				fi
+				case "$remoteIpset" in
+				ipset)
+					ips 'add' "${iface}" "$raddr" "${comment}: $raddr" || ipsFailFlag=1;;
+				dnsmasq.ipset)
+					ips 'add_dnsmasq' "${iface}" "$raddr" "${comment}" || ipsFailFlag=1;;
+				esac
 			fi
 		else
-			ips "add" "${iface}" "$raddr" "${comment}: $raddr" || ipsFailFlag=1
+			ips 'add' "${iface}" "$raddr" "${comment}: $raddr" || ipsFailFlag=1
 		fi
 	elif is_mac_address "$laddr"; then
 		insert_policy "$comment" "$iface" "$laddr" "$lport" "$raddr" "$rport" "$proto" "$chain"
@@ -427,7 +448,7 @@ r_process_policy(){
 }
 
 process_policy(){
-	local name comment iface laddr lport raddr rport param mark processPolicyStatus proto chain enabled
+	local name comment iface laddr lport raddr rport param mark processPolicyError processPolicyWarning proto chain enabled
 	config_get comment "$1" 'comment'
 	config_get name    "$1" 'name' 'blank'
 	config_get iface   "$1" 'interface'
@@ -435,7 +456,7 @@ process_policy(){
 	config_get lport   "$1" 'local_port'
 	config_get raddr   "$1" 'remote_address'
 	config_get rport   "$1" 'remote_port'
-	config_get proto   "$1" 'proto' 'tcp'
+	config_get proto   "$1" 'proto' 'all'
 	config_get chain   "$1" 'chain' 'PREROUTING'
 	config_get_bool enabled "$1" 'enabled' 1
 
@@ -460,9 +481,12 @@ process_policy(){
 	lport="${lport//  / }"; lport="${lport// /,}";
 	rport="${rport//  / }"; rport="${rport// /,}";
 	r_process_policy "$comment" "$iface" "$laddr" "$lport" "$raddr" "$rport" "$proto" "$chain"
-	if [ -n "$processPolicyStatus" ]; then
+	if [ -n "$processPolicyWarning" ]; then
+		warningStatusSummary="${warningStatusSummary}${processPolicyWarning}"
+	fi
+	if [ -n "$processPolicyError" ]; then
 		output_fail
-		errorStatusSummary="${errorStatusSummary}${processPolicyStatus}\\n"
+		errorStatusSummary="${errorStatusSummary}${processPolicyError}"
 	else
 		output_ok
 	fi
@@ -643,9 +667,14 @@ convert_config(){
 	sed -i 's/remote_ports/remote_port/g' "/etc/config/${packageName}"
 	sed -i 's/ipset_enabled/remote_ipset/g' "/etc/config/${packageName}"
 	sed -i 's/dnsmasq_enabled/dnsmasq_ipset/g' "/etc/config/${packageName}"
+	sed -i 's/enable_control/webui_enable_column/g' "/etc/config/${packageName}"
+	sed -i 's/proto_control/webui_protocol_column/g' "/etc/config/${packageName}"
+	sed -i 's/chain_control/webui_chain_column/g' "/etc/config/${packageName}"
+	sed -i 's/sort_control/webui_sorting/g' "/etc/config/${packageName}"
 	config_load "$packageName"
 	config_get_bool dnsmasqIpset        'config' 'dnsmasq_ipset' 0
 	config_get      remoteIpset         'config' 'remote_ipset'
+	config_get      webuiProtocol       'config' 'webui_supported_protocol'
 # shellcheck disable=SC2154
 	if [ "$dnsmasqIpset" = "1" ]; then
 		remoteIpset="dnsmasq.ipset";
@@ -656,6 +685,14 @@ convert_config(){
 	fi
 	uci -q del "$packageName.config.dnsmasq_ipset"
 	uci -q set "$packageName".config.remote_ipset="$remoteIpset"
+# shellcheck disable=SC2154
+	if [ -z "$webuiProtocol" ]; then
+		uci add_list "$packageName".config.webui_supported_protocol='tcp'
+		uci add_list "$packageName".config.webui_supported_protocol='udp'
+		uci add_list "$packageName".config.webui_supported_protocol='tcp udp'
+		uci add_list "$packageName".config.webui_supported_protocol='icmp'
+		uci add_list "$packageName".config.webui_supported_protocol='all'
+	fi
 	uci commit "$packageName"
 	for i in udp_proto_enabled forward_chain_enabled input_chain_enabled output_chain_enabled; do
 		grep -q "$i" "/etc/config/${packageName}" && output "${_WARNING_}: $i setting is not supported in ${serviceName}.\\n"
@@ -699,7 +736,7 @@ process_user_file(){
 }
 
 start_service() {
-	local serviceStatusSummary errorStatusSummary dnsmasqStoredHash dnsmasqNewHash i modprobeStatus=0
+	local serviceStatusSummary errorStatusSummary warningStatusSummary dnsmasqStoredHash dnsmasqNewHash i modprobeStatus=0
 	convert_config
 	is_enabled 'on_start' || return 1
 	is_wan_up || return 0
@@ -758,13 +795,15 @@ start_service() {
 			fi
 			output "$serviceName started on ${serviceStatusSummary}\\n"
 			if [ -z "$errorStatusSummary" ]; then
-#				output_okn
 				tmpfs 'set' "Success: ${serviceStatusSummary}"
 			else
-				output "with errors "
-				output_failn
+				output "With ERRORS:\\n"
 				output "${errorStatusSummary}"
 				tmpfs 'set' "Started on ${serviceStatusSummary} with error(s)"
+			fi
+			if [ -n "$warningStatusSummary" ]; then
+				output "With WARNINGS:\\n"
+				output "${warningStatusSummary}"
 			fi
 		fi
 		remove_lock
@@ -827,7 +866,6 @@ service_triggers() {
 }
 
 input() { local data; while read -r data; do echo "$data" | tee -a /var/${packageName}-support; done; }
-status() { support "$@"; }
 support() {
 	local dist vers out id s param status set_d set_p tableCount i=0 dev dev6
 	is_enabled
